/* main.c generated by valac 0.26.1, the Vala compiler
 * generated from main.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <stdlib.h>
#include <string.h>
#include <stdio.h>


#define ASYNC_BUS_TYPE_DEVICE (async_bus_device_get_type ())
#define ASYNC_BUS_DEVICE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), ASYNC_BUS_TYPE_DEVICE, AsyncBusDevice))
#define ASYNC_BUS_DEVICE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), ASYNC_BUS_TYPE_DEVICE, AsyncBusDeviceClass))
#define ASYNC_BUS_IS_DEVICE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), ASYNC_BUS_TYPE_DEVICE))
#define ASYNC_BUS_IS_DEVICE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), ASYNC_BUS_TYPE_DEVICE))
#define ASYNC_BUS_DEVICE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), ASYNC_BUS_TYPE_DEVICE, AsyncBusDeviceClass))

typedef struct _AsyncBusDevice AsyncBusDevice;
typedef struct _AsyncBusDeviceClass AsyncBusDeviceClass;
typedef struct _AsyncBusDevicePrivate AsyncBusDevicePrivate;

struct _AsyncBusDevice {
	GObject parent_instance;
	AsyncBusDevicePrivate * priv;
};

struct _AsyncBusDeviceClass {
	GObjectClass parent_class;
};


static gpointer async_bus_device_parent_class = NULL;

GType async_bus_device_get_type (void) G_GNUC_CONST;
enum  {
	ASYNC_BUS_DEVICE_DUMMY_PROPERTY
};
gint async_bus_device_main (gchar** args, int args_length1);
AsyncBusDevice* async_bus_device_new (void);
AsyncBusDevice* async_bus_device_construct (GType object_type);


gint async_bus_device_main (gchar** args, int args_length1) {
	gint result = 0;
	FILE* _tmp0_ = NULL;
	_tmp0_ = stdout;
	fprintf (_tmp0_, "Async Bus - Device\n");
	result = 0;
	return result;
}


int main (int argc, char ** argv) {
#if !GLIB_CHECK_VERSION (2,35,0)
	g_type_init ();
#endif
	return async_bus_device_main (argv, argc);
}


AsyncBusDevice* async_bus_device_construct (GType object_type) {
	AsyncBusDevice * self = NULL;
	self = (AsyncBusDevice*) g_object_new (object_type, NULL);
	return self;
}


AsyncBusDevice* async_bus_device_new (void) {
	return async_bus_device_construct (ASYNC_BUS_TYPE_DEVICE);
}


static void async_bus_device_class_init (AsyncBusDeviceClass * klass) {
	async_bus_device_parent_class = g_type_class_peek_parent (klass);
}


static void async_bus_device_instance_init (AsyncBusDevice * self) {
}


GType async_bus_device_get_type (void) {
	static volatile gsize async_bus_device_type_id__volatile = 0;
	if (g_once_init_enter (&async_bus_device_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (AsyncBusDeviceClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) async_bus_device_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (AsyncBusDevice), 0, (GInstanceInitFunc) async_bus_device_instance_init, NULL };
		GType async_bus_device_type_id;
		async_bus_device_type_id = g_type_register_static (G_TYPE_OBJECT, "AsyncBusDevice", &g_define_type_info, 0);
		g_once_init_leave (&async_bus_device_type_id__volatile, async_bus_device_type_id);
	}
	return async_bus_device_type_id__volatile;
}



